export const fileData = {
    id:1,
    name: "root",
    isFolder:true,
    items:[
        {
            id:2,
            name:"public",
            isFolder:true,
            items:[
                {
                id:3,
                name:"index.html",
                isFolder:false,
                },
                {
                id:4,
                name:"demo.html",
                isFolder:false,
                },
            ]
        },
        {
            id:5,
            name:"src",
            isFolder:true,
            items:[
                {
                    id:6,
                    name:"app.js",
                    isFolder:false,
                },
                {
                    id:7,
                    name:"index.js",
                    isFolder:false,
                },
                {
                    id:8,
                    name:"styles.css",
                    isFolder:false,
                },
            ]
        },
        {
            id:9,
            name:"package.json",
            isFolder:false,
        }
    ]
}
